### ISSUE TITLE
is some way to better detect DNS data?

### ISSUE THREAD

**Issue by rurirei** [eycorsican/go-tun2socks#147]
https://github.com/eycorsican/go-tun2socks/blob/256d181632768de921ebfb048b58b5cc51c2a51f/proxy/dnsfallback/udp.go#L29-L34 to check if port 53 is simple way but not steady enough. is there some way better?

addition, what is happening when enables DNS over TLS inside system Android, mostly it causes unavailbility of Fake DNS, and some other problem i had not known.

thanks for reply in advance.

**Comment by eycorsican** [comment]
There's [a fork of go-tun2socks](https://github.com/mellow-io/go-tun2socks/tree/master/common) with many extra features you might be interested. It's based on another fork of go-tun2socks that is used by the Google Play version of Kitsunebi.

**Comment by rurirei** [comment]
great thanks to make project so good open source of you.

though it do not solve my question in this post.

**Comment by rurirei** [comment]
addition, seems `leaf` is also a cross platform solution, what is the different purpose of it and `mellow`, is it on different language based? @eycorsican

**Comment by eycorsican** [comment]
leaf is an experimental project originally tries to address several unsolved issues in mellow/go-tun2socks/v2ray.

- The memory issue due to the Go language: https://github.com/eycorsican/go-tun2socks-mobile/issues/2
- The NAT issue in v2ray: https://github.com/v2ray/v2ray-core/issues/1429
- The performance issue in go-tun2socks due to poor `cgo` performance.

**Comment by rurirei** [comment]
got it. big thanks for all your great project.
